spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5000MB
spring.servlet.multipart.max-request-size=5000MB

spring.application.name=child-safety-service

# Railway PORT
server.port=${PORT:8082}

# Python AI Service URL
detection.python-service.url=${PYTHON_SERVICE_URL:http://localhost:5005}

# Database Service URL
detection.db-service.url=${DB_SERVICE_URL:http://localhost:8081}

logging.level.root=INFO