server.port=8088

flask.service.url=http://localhost:5003

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-swallow-size=500MB
server.tomcat.max-http-form-post-size=500MB

# ? ????? ??? WebSocket buffer
server.tomcat.websocket.buffer-size=1048576

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.toxicbert=INFO
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.socket=DEBUG