
server.port=8080

flask.service.url=http://localhost:5003

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.max-swallow-size=500MB

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.toxicbert=INFO
logging.level.org.springframework.web.client=DEBUG